//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCRLessonReport.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OCRLessonReport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson report recognition.
        /// </summary>
        public static string Application_Name {
            get {
                return ResourceManager.GetString("Application_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DSC02124 {
            get {
                object obj = ResourceManager.GetObject("DSC02124", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DSC02125 {
            get {
                object obj = ResourceManager.GetObject("DSC02125", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DSC02126 {
            get {
                object obj = ResourceManager.GetObject("DSC02126", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DSC02127 {
            get {
                object obj = ResourceManager.GetObject("DSC02127", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DSC02128 {
            get {
                object obj = ResourceManager.GetObject("DSC02128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DSC02129 {
            get {
                object obj = ResourceManager.GetObject("DSC02129", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap InternalImage {
            get {
                object obj = ResourceManager.GetObject("InternalImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Window_Button_Browse {
            get {
                return ResourceManager.GetString("Window_Button_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Window_Button_Close {
            get {
                return ResourceManager.GetString("Window_Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open cam.
        /// </summary>
        public static string Window_Button_OpenCam {
            get {
                return ResourceManager.GetString("Window_Button_OpenCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognize.
        /// </summary>
        public static string Window_Button_Recognize {
            get {
                return ResourceManager.GetString("Window_Button_Recognize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Window_Button_Save {
            get {
                return ResourceManager.GetString("Window_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shot.
        /// </summary>
        public static string Window_Button_Shot {
            get {
                return ResourceManager.GetString("Window_Button_Shot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source.
        /// </summary>
        public static string Window_GroupBox_DataSource {
            get {
                return ResourceManager.GetString("Window_GroupBox_DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Window_GroupBox_Image {
            get {
                return ResourceManager.GetString("Window_GroupBox_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognition.
        /// </summary>
        public static string Window_GroupBox_Recognition {
            get {
                return ResourceManager.GetString("Window_GroupBox_Recognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From File.
        /// </summary>
        public static string Window_Radio_File {
            get {
                return ResourceManager.GetString("Window_Radio_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string Window_Radio_Lib {
            get {
                return ResourceManager.GetString("Window_Radio_Lib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webcam.
        /// </summary>
        public static string Window_Radio_Webcam {
            get {
                return ResourceManager.GetString("Window_Radio_Webcam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging Data.
        /// </summary>
        public static string Window_TabControl_DebuggingData {
            get {
                return ResourceManager.GetString("Window_TabControl_DebuggingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognition.
        /// </summary>
        public static string Window_TabControl_Recognition {
            get {
                return ResourceManager.GetString("Window_TabControl_Recognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Window_TabControl_Settings {
            get {
                return ResourceManager.GetString("Window_TabControl_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file:.
        /// </summary>
        public static string Window_TextBlock_File {
            get {
                return ResourceManager.GetString("Window_TextBlock_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        public static string Window_TextBlock_Source {
            get {
                return ResourceManager.GetString("Window_TextBlock_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webcam control:.
        /// </summary>
        public static string Window_TextBlock_Webcam {
            get {
                return ResourceManager.GetString("Window_TextBlock_Webcam", resourceCulture);
            }
        }
    }
}
